spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:quidoitquoi}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings (optional)
spring.jpa.hibernate.ddl-auto=none

# Show JDBC logs
logging.level.org.springframework.jdbc=INFO
spring.application.name=api
spring.docker.compose.file=../docker-compose.yaml
