app.dev-user.username=${DEV_USER_USERNAME:frontend-dev}
app.dev-user.firstname=${DEV_USER_FIRSTNAME:Frontend}
app.dev-user.lastname=${DEV_USER_LASTNAME:Developer}
app.dev-user.email=${DEV_USER_EMAIL:frontend-dev@qui-doit-quoi.local}
app.dev-user.password=${DEV_USER_PASSWORD:frontend-dev-password}